### ISSUE TITLE
Add link to Swedish portal and language 

### ISSUE THREAD

**Issue by shahmanash** [melecoq/Living-Atlases-website#1]
https://github.com/melecoq/Living-Atlases-website/blob/192a9e17f9bfbbb8efdf86f015f08bc3e7075e86/_includes/docs.html#L73

https://bioatlas.se

https://github.com/melecoq/Living-Atlases-website/blob/192a9e17f9bfbbb8efdf86f015f08bc3e7075e86/_includes/docs.html#L76

English - Swedish

**Comment by melecoq** [comment]
Corrected.
